version: '3.8'

services:
  some-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pg_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: kirill-kent2006@mail.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - pg_network

  server:
    build: ./server
    ports:
      - "3000:3000"
    networks:
      - pg_network  

  client:
    build: ./client
    ports:
      - "80:80"
    networks:
      - pg_network

volumes:
  postgres_data:

networks:
  pg_network:
